Ogre_glTF: Ogre_glTF::glTFLoader Class Reference
Ogre_glTF::glTFLoader Class Reference final
Class that is responsible for initializing the library with the loader, and giving out.
#include <Ogre_glTF.hpp>
Classes
struct glTFLoaderImpl
Implementation of the glTF loader. Exist as a pImpl inside the glTFLoader class.
Public Member Functions
glTFLoader ()
Initialize the library by creating this object.
glTFLoader (glTFLoader &&other) noexcept
glTFLoader & operator= (glTFLoader &&other) noexcept
Move assign operator.
~glTFLoader ()
Deinitialize the library at this object destruction.
loaderAdapter loadFromFileSystem (const std::string &path) const
loaderAdapter loadGlbResource (const std::string &name) const
Load a GLB from Ogre's resource manager.
ModelInformation getModelData (const std::string &modelName, LoadFrom loadLocation) override
Get the model data. Contains everything you need to create object from the model contained on the glTF asset.
Ogre::Item * getItemFromResource (const std::string &name, Ogre::SceneManager *smgr) override
Ogre::Item * getItemFromFileSystem (const std::string &fileName, Ogre::SceneManager *smgr) override
MeshAndDataBlock getMeshFromResource (const std::string &name) override
MeshAndDataBlock getMeshFromFileSystem (const std::string &name) override
glTFLoader (const glTFLoader &)=delete
Deleted copy constructor.
glTFLoader & operator= (const glTFLoader &)=delete
Deleted assignment operator.
Public Member Functions inherited from Ogre_glTF::glTFLoaderInterface
virtual ~glTFLoaderInterface ()=default
Polymorphic dtor.
Additional Inherited Members
Public Types inherited from Ogre_glTF::glTFLoaderInterface
enum LoadFrom { FileSystem, ResourceManager }
location where to load the data
Detailed Description
Class that is responsible for initializing the library with the loader, and giving out.
Definition at line 147 of file Ogre_glTF.hpp.
Constructor & Destructor Documentation
glTFLoader()
glTFLoader::glTFLoader (glTFLoader && other) noexcept
Move constructor
Parameters
other object to move
Definition at line 284 of file Ogre_glTF.cpp.
Member Function Documentation
getItemFromFileSystem()
Ogre::Item * glTFLoader::getItemFromFileSystem (const std::string & fileName, Ogre::SceneManager * smgr) override virtual
Get you an item from a GLB or a GLTF file from the filesystem.
Parameters
fileName The name of the resource
smgr The scene manager where the Item will be used
Returns
pointer to a created item in your scene manager using the mesh in the glTF asset
Implements Ogre_glTF::glTFLoaderInterface.
Definition at line 251 of file Ogre_glTF.cpp.
References Ogre_glTF::loaderAdapter::getItem(), Ogre_glTF::loaderAdapter::isOk(), and loadFromFileSystem().
getItemFromResource()
Ogre::Item * glTFLoader::getItemFromResource (const std::string & name, Ogre::SceneManager * smgr) override virtual
Get you an item from a GLB file loaded inside an Ogre resource group
Parameters
name The name of the resource
smgr The scene manager where the Item will be used
Returns
pointer to a created item in your scene manager using the mesh in the glTF asset
Implements Ogre_glTF::glTFLoaderInterface.
Definition at line 237 of file Ogre_glTF.cpp.
References Ogre_glTF::loaderAdapter::getItem(), Ogre_glTF::loaderAdapter::isOk(), and loadGlbResource().
getMeshFromFileSystem()
MeshAndDataBlock glTFLoader::getMeshFromFileSystem (const std::string & name) override virtual
Gets you a mesh and a material datablock from GLB or a GLTF file from the filesystem
Parameters
name The name of the resource
Returns
a struct containing pointers to a mesh and a datablock
Implements Ogre_glTF::glTFLoaderInterface.
Definition at line 262 of file Ogre_glTF.cpp.
References Ogre_glTF::loaderAdapter::getDatablock(), Ogre_glTF::loaderAdapter::getMesh(), Ogre_glTF::loaderAdapter::isOk(), and loadFromFileSystem().
getMeshFromResource()
MeshAndDataBlock glTFLoader::getMeshFromResource (const std::string & name) override virtual
Get you a mesh and a material datablock from a GLB in the resource manager
Parameters
name The name of the resource
Returns
a struct containing pointers to a mesh and a datablock
Implements Ogre_glTF::glTFLoaderInterface.
Definition at line 273 of file Ogre_glTF.cpp.
References Ogre_glTF::loaderAdapter::getDatablock(), Ogre_glTF::loaderAdapter::getMesh(), Ogre_glTF::loaderAdapter::isOk(), and loadGlbResource().
loadFromFileSystem()
loaderAdapter glTFLoader::loadFromFileSystem (const std::string & path) const
Load a glTF text or binary file. Give you an adapter to use this file with Ogre
Parameters
path String containing the path to a file to load (either .glTF or .glc)
Definition at line 179 of file Ogre_glTF.cpp.
Referenced by getItemFromFileSystem(), getMeshFromFileSystem(), and getModelData().
The documentation for this class was generated from the following files:
C:/YbalridSoftware/AnnwvynSDK64/Ogre_glTF/include/Ogre_glTF.hpp
C:/YbalridSoftware/AnnwvynSDK64/Ogre_glTF/src/Ogre_glTF.cpp