Ogre_glTF: Ogre_glTF::loaderAdapter Class Reference
Ogre_glTF::loaderAdapter Class Reference
Class that hold the loaded content of a glTF file and that can create Ogre objects from it.
#include <Ogre_glTF.hpp>
Classes
struct impl
Implementaiton of the adapter.
Public Member Functions
loaderAdapter ()
This will aslo initialize the "pimpl" structure.
~loaderAdapter ()
This clear the pimpl structure.
loaderAdapter (const loaderAdapter &)=delete
Deleted copy constructor : non copyable class.
loaderAdapter & operator= (const loaderAdapter &)=delete
Deleted asignment constructor : non copyable class.
Ogre::Item * getItem (Ogre::SceneManager *smgr) const
loaderAdapter (loaderAdapter &&other) noexcept
loaderAdapter & operator= (loaderAdapter &&other) noexcept
Move assignemnt operator.
bool isOk () const
Return the current state of the adapter.
std::string getLastError () const
Return the last error generated by the underlying glTF loading library.
Friends
class glTFLoader
Detailed Description
Class that hold the loaded content of a glTF file and that can create Ogre objects from it.
Definition at line 25 of file Ogre_glTF.hpp.
Constructor & Destructor Documentation
loaderAdapter()
loaderAdapter::loaderAdapter (loaderAdapter && other) noexcept
Move constructor : object is movable
Parameters
other object to move
Definition at line 80 of file Ogre_glTF.cpp.
Member Function Documentation
getItem()
Ogre::Item * loaderAdapter::getItem (Ogre::SceneManager * smgr) const
Construct an item for this object
Parameters
smgr pointer to the scene manager where we are creating the item
Definition at line 62 of file Ogre_glTF.cpp.
References isOk().
Referenced by Ogre_glTF::glTFLoader::getItemFromFileSystem(), and Ogre_glTF::glTFLoader::getItemFromResource().
The documentation for this class was generated from the following files:
/home/ybalrid/dev/github/Ogre_glTF/include/Ogre_glTF.hpp
/home/ybalrid/dev/github/Ogre_glTF/src/Ogre_glTF.cpp